name: Variables

on:
  push:
     branches: [ main ]
  workflow_dispatch:
    inputs:
      skipJob: 
        type: boolean
        default: true
        required: false
        
env:
  SKIP_JOB: ${{ github.event.inputs.skipJob || false }}
  
jobs:
  tests:
    name: Tests
    if: github.event.inputs.skipJob == 'false' || github.event.inputs.skipJob == null
    runs-on: ubuntu-latest
    steps:
      - run: echo "run tests"
      
  after-tests:
    name: deploy
    needs: [ tests ]
    if: success() || github.event.inputs.skipJob
    runs-on: ubuntu-latest
    steps:
      - run: echo "run after test"
